services:

  backend:
    build: ./Backend/server
    image: marsa-backend:latest
    ports:
      - "82:82"
    env_file:
      - ./Backend/server/.env
    environment:
      - PORT=82
    restart: unless-stopped

  python:
    build: ./Backend/python
    image: marsa-python:latest
    ports:
      - "5000:5000"
    restart: unless-stopped
